### ISSUE TITLE
Define "everything collection(s)"

### ISSUE THREAD

**Issue by wjt** [endlessm/endless-key-collections#27]
Currently we have no clear definition of the complete universe of Endless Key content. The closest things we have are:

1. The union of all the JSON files in this repo (or I guess all the `*-0001.json` files)
2. Everything that's on key.endlessos.org

We know that 2 is too much: there's content on there that we don't want to be. (Once we have a machine-readable definition of "everything" we can work on automatically keeping key.endlessos.org in sync with that.)

Assuming that 1 is too little, we need to define 1 or more additional collections for “the rest”.

**Comment by hydrolet** [comment]
I have created an all_0001.json file and uploaded it to the repository. This file includes content from channels that are not represented in any of the pre-defined packs at this point in time. 

https://github.com/endlessm/endless-key-collections/tree/main/json

**Comment by wjt** [comment]
I'll leave verification here to e.g. @dylanmccall :)

**Comment by dylanmccall** [comment]
Okay, I took a look at this and it seems good to me. I made one small tweak: I renamed `all-0001.json` to `extras-0001.json`, since the name "all" (to me) suggests that this collection would be a concatenation of all the other collections. I was hoping to drop the `-0001` part of the name as well, since it doesn't seem necessary here, but there's a lot of plumbing in kolibri-explore-plugin which assumes a particular naming scheme, so I'll leave that alone for now.

I created a follow-up task to use this new collection in kolibri-explore-plugin:

- endlessm/kolibri-explore-plugin#606

Thanks for taking care of this, @hydrolet!

**Comment by erikos** [comment]
> I have created an all_0001.json file and uploaded it to the repository. This file includes content from channels that are not represented in any of the pre-defined packs at this point in time.
> 
> https://github.com/endlessm/endless-key-collections/tree/main/json

@hydrolet What are the channels we have now in the extras package? Can you list them here, please?

**Comment by hydrolet** [comment]
Channels include:

Blockly Games (I included this for the Spanish folder)
EiE Familias 
The SciGirls Collection (en español) 
PhET Interactive Simulations (es) 
Pilas Engine 
Sikana (Español) 
WiiXii 
електронні книги HarperCollins 
Українською 
California Academy of Sciences (en Español)
California Academy of Sciences

**Comment by hydrolet** [comment]
I have added more channels to the [extras pack](https://github.com/endlessm/endless-key-collections/blob/main/json/extras-0001.json). The pack now includes all channels not represented in a starter pack. The added channels are:

Beauty 4968191fba07548c9592fc174a70b5d6
Common Sense bcc6e12a0ddf4a17a8b600c6b880e3ed
CSpathshala (en) bbb4ea407a3c450cb18cbaa76f2d75cd
Fashion bf36d8e7e1ee56b194fe52cafbfd9db3
Financial Literacy 2b43973f53f1538bad5ece63ad847606
Free English with Hello 0418cc231e9c5513af0fff9f227f7172
Gardening efcc464be5a85ba5a58d1636b00313fc
Healthy Mind 4e413158eac55422a5343af9fcfa8d59
Thoughtful Learning 74f36493bb475b62935fa8705ed59fed
SAMHSA a8e6591f1afa426d859318a0a29d1237
Virtual Science Teachers eb4373b5da054c07879d0c969dc1976a

Custom presentations still needed for:
Blockly https://github.com/endlessm/endless-key-content-private/issues/88
Virtual Science Teachers https://github.com/endlessm/kolibri-explore-plugin/issues/731
SAMHSA (tbd)
