### ISSUE TITLE
Define release process

### ISSUE THREAD

**Issue by pwithnall** [endlessm/endless-key-collections#28]
While copying the endless-key-collections JSON files to kolibri-explore-plugin on EK Online, I spotted a few things which might need tidying up before we can automate that process.

 1. Should/Could the JSON content be installed to `KOLIBRI_HOMEDIR` rather than the Python dist-dir? It feels like user/curated content rather than code, and it probably should be stored in persistent storage rather than in somewhere which will be overwritten by a new VM image.
 2. Could we have tagged releases and release tarballs? If we are going to automatically deploy this to EK Online, currently the only option is to deploy `main`, which means we risk breaking EK Online if something broken is pushed to `main`.

**Comment by manuq** [comment]
Thanks for bringing this up, It is important for a new requirement we have in Endless Key: to decouple content updates from software updates. For sure we need tagged releases. And probably the installation place won't be a problem as we plan to fetch the JSON files from somewhere online (Github releases?) directly.

**Comment by pwithnall** [comment]
> For sure we need tagged releases.

OK. As a starting point, I’ve created [v0.1.0](https://github.com/endlessm/endless-key-collections/releases/tag/v0.1.0) as just a (signed) git tag of the latest `main`. If we want to build wheels or other packaging formats in future then that can be added later.

For the moment, though, having the release listed in GitHub means I can get the EK Online server to [query for releases](https://api.github.com/repos/endlessm/endless-key-collections/releases/latest) and download the tarball automatically.

> And probably the installation place won't be a problem as we plan to fetch the JSON files from somewhere online (Github releases?) directly.

I’m not sure I follow. Do you mean that the manual installation process of copying the JSON files onto the server will eventually be replaced by kolibri-explore-plugin automatically downloading them from endless-key-collections itself?

**Comment by manuq** [comment]
> > For sure we need tagged releases.
> 
> OK. As a starting point, I’ve created [v0.1.0](https://github.com/endlessm/endless-key-collections/releases/tag/v0.1.0) as just a (signed) git tag of the latest `main`. If we want to build wheels or other packaging formats in future then that can be added later.

Excellent!

> > And probably the installation place won't be a problem as we plan to fetch the JSON files from somewhere online (Github releases?) directly.
> 
> I’m not sure I follow. Do you mean that the manual installation process of copying the JSON files onto the server will eventually be replaced by kolibri-explore-plugin automatically downloading them from endless-key-collections itself?

Yes, the JSON files won't be needed inside the server, but will be GET from some URL, I guess the simplest is from Github. Although that means depending on Github at run-time.

**Comment by pwithnall** [comment]
OK, I guess from a server deployment point of view this is fixed with https://github.com/endlessm/eos-administration/pull/1335 then.
